apiVersion: apps/v1
kind: Deployment
metadata:
  name: muzammilpeer-nginx-app
spec:
  selector:
    matchLabels:
      app: muzammilpeer-nginx-app
  replicas: 1
  template:
    metadata:
      labels:
        app: muzammilpeer-nginx-app
    spec:
      containers:
      - name: nginx
        image: muzammilpeer/nginx-static:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: muzammilpeer-nginx-service
spec:
  type: NodePort
  ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30100
  selector:
    app: muzammilpeer-nginx-app